### ISSUE TITLE
Possibility to fix this warning about N-API?

### ISSUE THREAD

**Issue by Deisss** [sonicdoe/ced#1]
Hi,

First of all thank you for this port, it's already helpful to me!

Second, I see there is this warning starting everytime I start the project with your plugin:
(node:79533) Warning: N-API is an experimental feature and could change at any time.

Could it be possible to fix this (from what I can see it doesn't look like a "normal" gyp plugin so maybe it's related to this)?

Regards

**Comment by sonicdoe** [comment]
Thank you for the kind words! This package uses [N-API](https://nodejs.org/dist/latest-v10.x/docs/api/n-api.html#n_api_n_api) which is a newer (and more stable) way of writing native modules. Coincidentally, [Node.js v8.12.0](https://nodejs.org/en/blog/release/v8.12.0/), which was released 3 days ago, no longer considers N-API experimental so you should no longer encounter this warning with the lastest Node.js versions.

**Comment by Deisss** [comment]
Oh ok perfect then :)

Again thank you for this port :)
