### ISSUE TITLE
is this addon safe to use with electron while allowRendererProcessReuse enabled?

### ISSUE THREAD

**Issue by bruceauyeung** [sonicdoe/ced#7]
electron's `allowRendererProcessReuse` may run different node contexts in one process, similar with node worker threads.
native modules must be either context-aware or napi to work with `allowRendererProcessReuse`
is this addon safe to use with electron while allowRendererProcessReuse enabled?
if not, is there any plan?

**Comment by sonicdoe** [comment]
I haven’t checked in detail, but this package is built using [N-API](https://nodejs.org/api/n-api.html), so I think it should be compatible.
